name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk zip unzip libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer Cython==3.0.11
          pip install legacy-cgi
          PYLIB=$(python3 -c "import sysconfig; print(sysconfig.get_paths()['purelib'])")
          echo "import sys; import legacy_cgi; sys.modules['cgi'] = legacy_cgi" > $PYLIB/sitecustomize.py
          python3 -c "import cgi; print('cgi fixed')"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Moses-Robot-APK
          path: bin/*.apk
